name: clang-tidy

on: pull_request
  # push:
  #   branches: [ $default-branch ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    env:
      TOOL: clang-tidy-analyzer
      TRAVIS_BRANCH: ${{ github.base_ref }} 
      TRAVIS_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
      BASE_COMMIT: ${{ github.event.pull_request.base.sha }}
    steps:
    - uses: actions/checkout@v2
    - name: Fetch base_ref HEAD
      run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
    - name: install clang-tidy
      run: sudo apt-get install -y clang-tidy
    - name: run clang-tidy script
      run: scripts/clang-tidy.sh